/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trekmosaic;

import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class gearpage2 extends javax.swing.JFrame {

    /**
     * Creates new form gearpage2
     */
    public gearpage2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        item1Panel = new javax.swing.JPanel();
        imagePanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameOfItem = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        shoeResntButton1 = new javax.swing.JButton();
        clickCount1 = new javax.swing.JLabel();
        featureItem2 = new javax.swing.JLabel();
        item1feature3 = new javax.swing.JLabel();
        featureItem1 = new javax.swing.JLabel();
        item2Panel = new javax.swing.JPanel();
        imagePanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        shoeResntButton2 = new javax.swing.JButton();
        clickCount2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        costButton = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bglabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Swis721 Blk BT", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("RENT GEARS");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        item1Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        item1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePanel1.setBackground(new java.awt.Color(204, 204, 204));
        imagePanel1.setForeground(new java.awt.Color(204, 204, 204));
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/shoe resizesd.png"))); // NOI18N
        imagePanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        item1Panel.add(imagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 142, 129));

        nameOfItem.setBackground(new java.awt.Color(153, 153, 153));
        nameOfItem.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nameOfItem.setForeground(new java.awt.Color(0, 51, 51));
        nameOfItem.setText("TREK 100 SHOES");
        item1Panel.add(nameOfItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 138, 142, 33));

        priceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        priceLabel.setText("PRICE :  Rs. 180 /-");
        item1Panel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 27));

        shoeResntButton1.setBackground(new java.awt.Color(204, 204, 255));
        shoeResntButton1.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        shoeResntButton1.setText("RENT ");
        shoeResntButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        shoeResntButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoeResntButton1ActionPerformed(evt);
            }
        });
        item1Panel.add(shoeResntButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 76, 25));

        clickCount1.setBackground(new java.awt.Color(153, 153, 153));
        clickCount1.setText("   0");
        clickCount1.setToolTipText("");
        clickCount1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        item1Panel.add(clickCount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 27, 27));

        featureItem2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        featureItem2.setText("WATERPROOF");
        item1Panel.add(featureItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 70, 135, 28));

        item1feature3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        item1feature3.setText("LIGHTWEIGHT");
        item1Panel.add(item1feature3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 104, 135, 28));

        featureItem1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        featureItem1.setText("ROBUST");
        item1Panel.add(featureItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 30, 135, 28));

        jPanel1.add(item1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 230));

        item2Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imagePanel2.setBackground(new java.awt.Color(204, 204, 204));
        imagePanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/headlampresizes.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("HEADLAMP");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("PRICE : Rs 25 /-");

        shoeResntButton2.setBackground(new java.awt.Color(204, 204, 255));
        shoeResntButton2.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        shoeResntButton2.setText("RENT ");
        shoeResntButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        shoeResntButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoeResntButton2ActionPerformed(evt);
            }
        });

        clickCount2.setBackground(new java.awt.Color(153, 153, 153));
        clickCount2.setText("   0");
        clickCount2.setToolTipText("");
        clickCount2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setText("8 hr Battery LIfe");

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setText("STURDY");

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel15.setText("Hands free Torch");

        javax.swing.GroupLayout item2PanelLayout = new javax.swing.GroupLayout(item2Panel);
        item2Panel.setLayout(item2PanelLayout);
        item2PanelLayout.setHorizontalGroup(
            item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2PanelLayout.createSequentialGroup()
                .addGroup(item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(item2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(7, 7, 7)
                .addComponent(shoeResntButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clickCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item2PanelLayout.setVerticalGroup(
            item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2PanelLayout.createSequentialGroup()
                .addGroup(item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(item2PanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(item2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shoeResntButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clickCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel1.add(item2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 300, 230));

        costButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        costButton.setText("TOTAL COST : Rs. 0 /-");
        costButton.setOpaque(true);
        jPanel1.add(costButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 210, 60));

        jButton2.setText("PURCHASE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 130, 40));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 90, 30));

        bglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/BGpict.jpg"))); // NOI18N
        jPanel1.add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1081, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1081, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shoeResntButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoeResntButton1ActionPerformed
        // TODO add your handling code here:
        count++;
        UserData.cost += 180;
        clickCount1.setText("  " + count);
        price = price + 180;
        costButton.setText("TOTAL COST : " + price);
    }//GEN-LAST:event_shoeResntButton1ActionPerformed

    private void shoeResntButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoeResntButton2ActionPerformed
        // TODO add your handling code here:
        count2++;
        UserData.cost += 25;
        price = price + 25;
        clickCount2.setText("  " + count);
        costButton.setText("TOTAL COST : " + price);
    }//GEN-LAST:event_shoeResntButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "purchase details sent on email");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gearpage2.this.dispose();
        dashboard_v2 db = new dashboard_v2();
            db.setLocationRelativeTo(null);
            db.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    private void addItem1(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addItem2(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addItem3(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addItem4(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addItem5(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addItem6(String name,String feature1, String feature2, String feature3, int price ){
        
    }
    private void addImagePanel(String filename){
       ImagePanel = new javax.swing.JPanel();
       
       ImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
       jPanel1.add(ImagePanel);
       ImagePanel.setBounds(10, 90, 130, 130);
       
       ImageLabel = new javax.swing.JLabel();
       ImageIcon icon = new ImageIcon(filename);
       ImageLabel.setIcon(icon);
       ImagePanel.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));
       
    ImagePanel.revalidate();
    ImagePanel.repaint();
       
    }
      private ImageIcon getImageFromDatabase(String trekName) throws SQLException {

        Connection con = DatabaseConnection.connect();
        String selectQuery = "SELECT image FROM trek_data WHERE name = ?";
        try (PreparedStatement statement = con.prepareStatement(selectQuery)) {
            statement.setString(1, trekName);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Blob imageBlob = resultSet.getBlob("image");
                    byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
                    ImageIcon imageIcon = new ImageIcon(imageBytes);
                    return imageIcon;
                }
            }
        } catch (SQLException ex) {
        } finally {
            DatabaseConnection.disconnect();
        }
        return null;
    }

        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gearpage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gearpage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gearpage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gearpage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gearpage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bglabel;
    private javax.swing.JLabel clickCount1;
    private javax.swing.JLabel clickCount2;
    private javax.swing.JLabel costButton;
    private javax.swing.JLabel featureItem1;
    private javax.swing.JLabel featureItem2;
    private javax.swing.JPanel imagePanel1;
    private javax.swing.JPanel imagePanel2;
    private javax.swing.JPanel item1Panel;
    private javax.swing.JLabel item1feature3;
    private javax.swing.JPanel item2Panel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameOfItem;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton shoeResntButton1;
    private javax.swing.JButton shoeResntButton2;
    // End of variables declaration//GEN-END:variables
    private int count = 0;
    private int count2 = 0;
    private int price = 0;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImageLabel;
}
